In [100]:
import pandas as pd

In [101]:
df = pd.read_csv("../../04_datasets/nfl_dataset_v3.csv")
df.head()

,Unnamed: 0,season,week,awayteam,hometeam,awayscore,homescore,idgame,score_abs,winner_home,...,capacity,people,attendance_info,month,dayofmonth,dayofweek,hour,minute,win_streak,lose_streak
0,0,2017,9,Bengals,Jaguars,7,23,400951753,16,1,...,67858,89.0,1,11,5,6,18,0,0.0,1.0
1,4,2017,4,Bills,Falcons,23,17,400951685,-6,0,...,75000,95.0,1,10,1,6,17,0,2.0,0.0
2,8,2017,4,Saints,Dolphins,20,0,400950241,-20,0,...,86000,98.0,1,10,1,6,13,30,0.0,2.0
3,12,2017,4,Bears,Packers,14,35,400951678,21,1,...,81041,97.0,1,9,29,4,0,25,0.0,1.0
4,16,2017,16,Colts,Ravens,16,23,400951596,7,1,...,70745,100.0,1,12,23,5,21,30,0.0,6.0

#### Basic preprocessing

- Columns to be removed because they reveal the winner: 'awayscore', 'homescore', 'score_abs', 'winner_team', 'winner_away'
- Columns to be removed because they are in double: all the columns of the metrics without the 'MA' at the end (moving average)

In [102]:
df = df.drop(columns=['Unnamed: 0', 'capacity', 'concat', 'game_date', 'delta_match', 'date','awayscore', 'homescore', 'score_abs', 'winner_team', 'winner_away', 'attendance_info', 'location_x', 'location_y', 'hour', 'minute', 'team'])

- Removing the duplicates in the idgame

In [103]:
# cheking the amount of games in the dataframe
len(df.idgame.unique())

1289

In [104]:
# identifying the double
df.duplicated('idgame')

0       False
1       False
2       False
3       False
4       False
        ...
1284    False
1285    False
1286    False
1287    False
1288    False
Length: 1289, dtype: bool

In [105]:
print(df.columns.tolist())

['season', 'week', 'awayteam', 'hometeam', 'idgame', 'winner_home', 'home_coach', 'away_coach', 'weather_type', 'temperature', 'humidity', 'wind', 'pass_yds_MA_5', 'pass_td_MA_5', 'rush_yds_MA_5', 'rush_td_MA_5', 'rec_yds_MA_5', 'rec_td_MA_5', 'fumbles_MA_5', 'fumbles_rec_MA_5', 'defense_sacks_MA_5', 'defense_td_MA_5', 'interceptions_MA_5', 'interceptions_td_MA_5', 'kicks_return_yds_MA_5', 'kicks_return_td_MA_5', 'punt_return_yds_MA_5', 'kicking_pct_MA_5', 'stade', 'attendance', 'people', 'month', 'dayofmonth', 'dayofweek', 'win_streak', 'lose_streak']

- Integrating a new column 'Playing_at_home' to distinguish the opponent from the localisation of the game

In [106]:
# creating a new column
df['playing_at_home'] = 1

# renaming the awayteam column
df = df.rename(columns = {'awayteam':'opponent'})

##### Basic analysis

In [107]:
print("Number of rows : {}".format(df.shape[0]))
print()

print("Basics statistics: ")
data_desc = df.describe(include='all')
display(data_desc)
print()

print("Percentage of missing values: ")
display(100*df.isnull().sum()/df.shape[0])

Number of rows : 1289

Basics statistics:

,season,week,opponent,hometeam,idgame,winner_home,home_coach,away_coach,weather_type,temperature,...,kicking_pct_MA_5,stade,attendance,people,month,dayofmonth,dayofweek,win_streak,lose_streak,playing_at_home
count,1289.000000,1289.000000,1289,1289,1.289000e+03,1289.000000,1289,1289,1289,1289.000000,...,1209.000000,1289,1140.000000,1140.000000,1289.000000,1289.000000,1289.000000,1275.000000,1275.000000,1289.0
unique,NaN,NaN,32,32,NaN,NaN,63,63,7,NaN,...,NaN,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,Cowboys,Jaguars,NaN,NaN,John Harbaugh,Ron Rivera,cloudy,NaN,...,NaN,MetLife Stadium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,41,41,NaN,NaN,41,41,768,NaN,...,NaN,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,2019.027153,9.175330,NaN,NaN,4.011341e+08,0.539178,NaN,NaN,NaN,57.233514,...,72.989264,NaN,61886.508772,88.013158,10.254461,16.082234,5.098526,1.032941,1.349804,1.0
std,1.422984,5.062066,NaN,NaN,1.338832e+05,0.498656,NaN,NaN,NaN,21.706911,...,17.842267,NaN,19059.984436,24.114280,2.123613,8.765195,1.920486,1.603718,2.210647,0.0
min,2017.000000,1.000000,NaN,NaN,4.009502e+08,0.000000,NaN,NaN,NaN,1.000000,...,6.660000,NaN,748.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.0
25%,2018.000000,5.000000,NaN,NaN,4.010308e+08,0.000000,NaN,NaN,NaN,45.000000,...,60.000000,NaN,60546.750000,91.000000,10.000000,9.000000,6.000000,0.000000,0.000000,1.0
50%,2019.000000,9.000000,NaN,NaN,4.011280e+08,1.000000,NaN,NaN,NaN,63.000000,...,75.000000,NaN,66880.500000,97.000000,11.000000,16.000000,6.000000,0.000000,1.000000,1.0
75%,2020.000000,14.000000,NaN,NaN,4.012203e+08,1.000000,NaN,NaN,NaN,72.000000,...,85.000000,NaN,71865.250000,100.000000,12.000000,24.000000,6.000000,1.500000,2.000000,1.0
max,2021.000000,18.000000,NaN,NaN,4.013266e+08,1.000000,NaN,NaN,NaN,103.000000,...,100.000000,NaN,93503.000000,100.000000,12.000000,31.000000,6.000000,14.000000,20.000000,1.0

Percentage of missing values:

season                    0.000000
week                      0.000000
opponent                  0.000000
hometeam                  0.000000
idgame                    0.000000
winner_home               0.000000
home_coach                0.000000
away_coach                0.000000
weather_type              0.000000
temperature               0.000000
humidity                  0.000000
wind                      0.000000
pass_yds_MA_5             6.206362
pass_td_MA_5              6.206362
rush_yds_MA_5             6.206362
rush_td_MA_5              6.206362
rec_yds_MA_5              6.206362
rec_td_MA_5               6.206362
fumbles_MA_5              6.206362
fumbles_rec_MA_5          6.206362
defense_sacks_MA_5        6.206362
defense_td_MA_5           6.206362
interceptions_MA_5        6.206362
interceptions_td_MA_5     6.206362
kicks_return_yds_MA_5     6.206362
kicks_return_td_MA_5      6.206362
punt_return_yds_MA_5      6.206362
kicking_pct_MA_5          6.206362
stade                     0.000000
attendance               11.559348
people                   11.559348
month                     0.000000
dayofmonth                0.000000
dayofweek                 0.000000
win_streak                1.086113
lose_streak               1.086113
playing_at_home           0.000000
dtype: float64

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1289 entries, 0 to 1288
Data columns (total 37 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   season                 1289 non-null   int64
 1   week                   1289 non-null   int64
 2   opponent               1289 non-null   object
 3   hometeam               1289 non-null   object
 4   idgame                 1289 non-null   int64
 5   winner_home            1289 non-null   int64
 6   home_coach             1289 non-null   object
 7   away_coach             1289 non-null   object
 8   weather_type           1289 non-null   object
 9   temperature            1289 non-null   int64
 10  humidity               1289 non-null   int64
 11  wind                   1289 non-null   int64
 12  pass_yds_MA_5          1209 non-null   float64
 13  pass_td_MA_5           1209 non-null   float64
 14  rush_yds_MA_5          1209 non-null   float64
 15  rush_td_MA_5           1209 non-null   float64
 16  rec_yds_MA_5           1209 non-null   float64
 17  rec_td_MA_5            1209 non-null   float64
 18  fumbles_MA_5           1209 non-null   float64
 19  fumbles_rec_MA_5       1209 non-null   float64
 20  defense_sacks_MA_5     1209 non-null   float64
 21  defense_td_MA_5        1209 non-null   float64
 22  interceptions_MA_5     1209 non-null   float64
 23  interceptions_td_MA_5  1209 non-null   float64
 24  kicks_return_yds_MA_5  1209 non-null   float64
 25  kicks_return_td_MA_5   1209 non-null   float64
 26  punt_return_yds_MA_5   1209 non-null   float64
 27  kicking_pct_MA_5       1209 non-null   float64
 28  stade                  1289 non-null   object
 29  attendance             1140 non-null   float64
 30  people                 1140 non-null   float64
 31  month                  1289 non-null   int64
 32  dayofmonth             1289 non-null   int64
 33  dayofweek              1289 non-null   int64
 34  win_streak             1275 non-null   float64
 35  lose_streak            1275 non-null   float64
 36  playing_at_home        1289 non-null   int64
dtypes: float64(20), int64(11), object(6)
memory usage: 372.7+ KB

#### Test with a logistic regression

In [109]:
df_rl = df

In [110]:
df_rl = df_rl.drop(columns=['idgame'])

In [111]:
df_rl.columns

Index(['season', 'week', 'opponent', 'hometeam', 'winner_home', 'home_coach',
       'away_coach', 'weather_type', 'temperature', 'humidity', 'wind',
       'pass_yds_MA_5', 'pass_td_MA_5', 'rush_yds_MA_5', 'rush_td_MA_5',
       'rec_yds_MA_5', 'rec_td_MA_5', 'fumbles_MA_5', 'fumbles_rec_MA_5',
       'defense_sacks_MA_5', 'defense_td_MA_5', 'interceptions_MA_5',
       'interceptions_td_MA_5', 'kicks_return_yds_MA_5',
       'kicks_return_td_MA_5', 'punt_return_yds_MA_5', 'kicking_pct_MA_5',
       'stade', 'attendance', 'people', 'month', 'dayofmonth', 'dayofweek',
       'win_streak', 'lose_streak', 'playing_at_home'],
      dtype='object')

In [112]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import numpy as np

In [113]:
# defining columns that will not be taken into account in the model because they are redundant
#redundant_columns = ['idgame', 'minute', 'hour', 'attendance', 'people', 'win']

In [114]:
# defining a list of columns to be excluded from X
#to_be_excluded = ['winner_home', 'idgame', 'minute', 'hour', 'attendance', 'people', 'win']

In [116]:
Y = df.loc[:,"winner_home"]
X = df.loc[:,[c for c in df.columns if c!='winner_home']]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1, random_state=0, stratify=Y)

# select automatically the numerical and categorical columns
num_col = X.select_dtypes([np.number]).columns
cat_col = X.select_dtypes("object").columns

# Create pipeline for numeric features
numeric_features = X.select_dtypes([np.number]).columns 
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')), # missing values in Age will be replaced by columns' mean
    ('scaler', StandardScaler())])

# Create pipeline for categorical features
categorical_features = X.select_dtypes("object").columns 
categorical_transformer = Pipeline(
    steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')), # missing values will be replaced by most frequent value
    ('encoder', OneHotEncoder(drop='first')) # first column will be dropped to avoid creating correlations between features
    ])

# Use ColumnTranformer to make a preprocessor object that describes all the treatments to be done
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

model = LogisticRegression()
model.fit(X_train, Y_train)

Y_train_pred = model.predict(X_train)
Y_test_pred = model.predict(X_test)

print("Accuracy on training set : ", accuracy_score(Y_train, Y_train_pred))
print("Accuracy on test set : ", accuracy_score(Y_test, Y_test_pred))

Accuracy on training set :  0.7224137931034482
Accuracy on test set :  0.5736434108527132

C:\Users\alice\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

#### Test with a random forest

In [117]:
!pip install xgboost
from xgboost import XGBRegressor
from sklearn.ensemble import AdaBoostRegressor

[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: C:\Users\alice\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Collecting xgboost
  Downloading xgboost-1.6.1-py3-none-win_amd64.whl (125.4 MB)
     -------------------------------------- 125.4/125.4 MB 9.3 MB/s eta 0:00:00
Requirement already satisfied: scipy in c:\users\alice\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from xgboost) (1.8.1)
Requirement already satisfied: numpy in c:\users\alice\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from xgboost) (1.22.4)
Installing collected packages: xgboost
Successfully installed xgboost-1.6.1

In [ ]:
regressor_ada = AdaBoostRegressor()
regressor_ada.fit(X_train, Y_train)

print("score Adaboost default train {}".format(regressor_ada.score(X_train, y_train)))
print("\n")
print("score Adaboost default test {}".format(regressor_ada.score(X_test, y_test)))